// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/mjölnir/mjölnir.proto

package mjölnir

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlkRef_Encoding int32

const (
	BlkRef_ERASURE BlkRef_Encoding = 0
)

var BlkRef_Encoding_name = map[int32]string{
	0: "ERASURE",
}

var BlkRef_Encoding_value = map[string]int32{
	"ERASURE": 0,
}

func (x BlkRef_Encoding) String() string {
	return proto.EnumName(BlkRef_Encoding_name, int32(x))
}

func (BlkRef_Encoding) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_266c39c16c9fab21, []int{2, 0}
}

type Inode struct {
	Perms                uint32    `protobuf:"varint,1,opt,name=perms,proto3" json:"perms,omitempty"`
	IsDir                bool      `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size                 int64     `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Dirents              []*DirEnt `protobuf:"bytes,4,rep,name=dirents,proto3" json:"dirents,omitempty"`
	Blks                 []*BlkRef `protobuf:"bytes,5,rep,name=blks,proto3" json:"blks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Inode) Reset()         { *m = Inode{} }
func (m *Inode) String() string { return proto.CompactTextString(m) }
func (*Inode) ProtoMessage()    {}
func (*Inode) Descriptor() ([]byte, []int) {
	return fileDescriptor_266c39c16c9fab21, []int{0}
}

func (m *Inode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inode.Unmarshal(m, b)
}
func (m *Inode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inode.Marshal(b, m, deterministic)
}
func (m *Inode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inode.Merge(m, src)
}
func (m *Inode) XXX_Size() int {
	return xxx_messageInfo_Inode.Size(m)
}
func (m *Inode) XXX_DiscardUnknown() {
	xxx_messageInfo_Inode.DiscardUnknown(m)
}

var xxx_messageInfo_Inode proto.InternalMessageInfo

func (m *Inode) GetPerms() uint32 {
	if m != nil {
		return m.Perms
	}
	return 0
}

func (m *Inode) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *Inode) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Inode) GetDirents() []*DirEnt {
	if m != nil {
		return m.Dirents
	}
	return nil
}

func (m *Inode) GetBlks() []*BlkRef {
	if m != nil {
		return m.Blks
	}
	return nil
}

type DirEnt struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirEnt) Reset()         { *m = DirEnt{} }
func (m *DirEnt) String() string { return proto.CompactTextString(m) }
func (*DirEnt) ProtoMessage()    {}
func (*DirEnt) Descriptor() ([]byte, []int) {
	return fileDescriptor_266c39c16c9fab21, []int{1}
}

func (m *DirEnt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirEnt.Unmarshal(m, b)
}
func (m *DirEnt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirEnt.Marshal(b, m, deterministic)
}
func (m *DirEnt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirEnt.Merge(m, src)
}
func (m *DirEnt) XXX_Size() int {
	return xxx_messageInfo_DirEnt.Size(m)
}
func (m *DirEnt) XXX_DiscardUnknown() {
	xxx_messageInfo_DirEnt.DiscardUnknown(m)
}

var xxx_messageInfo_DirEnt proto.InternalMessageInfo

func (m *DirEnt) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DirEnt) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BlkRef struct {
	Encoding             BlkRef_Encoding `protobuf:"varint,1,opt,name=encoding,proto3,enum=mjolnir.BlkRef_Encoding" json:"encoding,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BlkRef) Reset()         { *m = BlkRef{} }
func (m *BlkRef) String() string { return proto.CompactTextString(m) }
func (*BlkRef) ProtoMessage()    {}
func (*BlkRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_266c39c16c9fab21, []int{2}
}

func (m *BlkRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlkRef.Unmarshal(m, b)
}
func (m *BlkRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlkRef.Marshal(b, m, deterministic)
}
func (m *BlkRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlkRef.Merge(m, src)
}
func (m *BlkRef) XXX_Size() int {
	return xxx_messageInfo_BlkRef.Size(m)
}
func (m *BlkRef) XXX_DiscardUnknown() {
	xxx_messageInfo_BlkRef.DiscardUnknown(m)
}

var xxx_messageInfo_BlkRef proto.InternalMessageInfo

func (m *BlkRef) GetEncoding() BlkRef_Encoding {
	if m != nil {
		return m.Encoding
	}
	return BlkRef_ERASURE
}

func init() {
	proto.RegisterEnum("mjolnir.BlkRef_Encoding", BlkRef_Encoding_name, BlkRef_Encoding_value)
	proto.RegisterType((*Inode)(nil), "mjolnir.Inode")
	proto.RegisterType((*DirEnt)(nil), "mjolnir.DirEnt")
	proto.RegisterType((*BlkRef)(nil), "mjolnir.BlkRef")
}

func init() { proto.RegisterFile("pkg/mjölnir/mjölnir.proto", fileDescriptor_266c39c16c9fab21) }

var fileDescriptor_266c39c16c9fab21 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0xb5, 0x5b, 0xdb, 0xcd, 0x3b, 0x9c, 0x12, 0x14, 0x03, 0xbe, 0x94, 0xfa, 0xd2, 0xa1, 0xb4,
	0x30, 0xfd, 0x01, 0xc7, 0xfa, 0xe0, 0x6b, 0x44, 0x04, 0x5f, 0xc4, 0x2e, 0xb1, 0xde, 0xb5, 0x49,
	0x4a, 0x52, 0x11, 0xfc, 0x12, 0xbf, 0xc4, 0x1f, 0xf0, 0xc7, 0x64, 0x69, 0x37, 0x64, 0x6f, 0xe7,
	0xe6, 0x9c, 0x93, 0x73, 0x38, 0x70, 0xd1, 0x54, 0x65, 0x26, 0xd7, 0xbf, 0x3f, 0xb5, 0x42, 0xb3,
	0x03, 0x69, 0x63, 0x74, 0xab, 0xc9, 0x48, 0xae, 0xf5, 0xe6, 0x8c, 0xbf, 0x3d, 0x08, 0xee, 0x95,
	0xe6, 0x82, 0x9c, 0x42, 0xd0, 0x08, 0x23, 0x2d, 0xf5, 0x22, 0x2f, 0x39, 0x62, 0xdd, 0x41, 0xce,
	0x20, 0x44, 0xfb, 0xc2, 0xd1, 0xd0, 0x41, 0xe4, 0x25, 0x63, 0x16, 0xa0, 0x5d, 0xa2, 0x21, 0x04,
	0x7c, 0x8b, 0x5f, 0x82, 0x0e, 0x23, 0x2f, 0x19, 0x32, 0x87, 0xc9, 0x0c, 0x46, 0x1c, 0x8d, 0x50,
	0xad, 0xa5, 0x7e, 0x34, 0x4c, 0x26, 0xf3, 0xe3, 0xb4, 0x4f, 0x49, 0x97, 0x68, 0x72, 0xd5, 0xb2,
	0x2d, 0x4f, 0x2e, 0xc1, 0x2f, 0xea, 0xca, 0xd2, 0x60, 0x4f, 0xb7, 0xa8, 0x2b, 0x26, 0xde, 0x98,
	0x23, 0xe3, 0x6b, 0x08, 0x3b, 0xdf, 0x26, 0x4d, 0xbd, 0x4a, 0xe1, 0x9a, 0x1d, 0x32, 0x87, 0xc9,
	0x14, 0x06, 0xc8, 0x5d, 0x29, 0x9f, 0x0d, 0x90, 0xc7, 0x4f, 0x10, 0x76, 0x6e, 0x72, 0x0b, 0x63,
	0xa1, 0x56, 0x9a, 0xa3, 0x2a, 0x9d, 0x63, 0x3a, 0xa7, 0x7b, 0x01, 0x69, 0xde, 0xf3, 0x6c, 0xa7,
	0x8c, 0xcf, 0x61, 0xbc, 0x7d, 0x25, 0x13, 0x18, 0xe5, 0xec, 0xee, 0xe1, 0x91, 0xe5, 0x27, 0x07,
	0x8b, 0xab, 0xe7, 0x59, 0x89, 0xed, 0xfb, 0x47, 0x91, 0xae, 0xb4, 0xcc, 0x5a, 0x2d, 0x3f, 0xb1,
	0xae, 0x50, 0x64, 0xfd, 0x97, 0xd9, 0xff, 0x99, 0x8b, 0xd0, 0xcd, 0x7b, 0xf3, 0x17, 0x00, 0x00,
	0xff, 0xff, 0x20, 0x76, 0xf4, 0x8e, 0x7d, 0x01, 0x00, 0x00,
}
